# Generated by Django 3.0.3 on 2020-03-01 20:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=5000)),
                ('sender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sending_date', models.DateTimeField(default=datetime.datetime(2020, 3, 1, 20, 43, 39, 263443))),
                ('contact_consent', models.BooleanField()),
            ],
        ),
    ]
