# Generated by Django 3.0.3 on 2020-07-25 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='sending_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 25, 20, 30, 14, 580830, tzinfo=utc)),
        ),
    ]
