# Generated by Django 3.0.3 on 2020-03-01 21:02

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0002_contactformmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='sending_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 21, 2, 11, 574988, tzinfo=utc)),
        ),
    ]
