# Generated by Django 3.0.3 on 2020-03-12 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(default=None, null=True)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('registration_token', models.CharField(default=None, max_length=1000, null=True)),
                ('confirmed_token', models.CharField(default=None, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmailUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('linked_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProfile')),
            ],
        ),
    ]
