# Generated by Django 3.0.3 on 2020-02-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmailUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('linked_profile',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientProfile')),
            ],
        ),
    ]
