# Generated by Django 3.0.3 on 2020-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='cos',
            field=models.CharField(default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='cos',
            field=models.CharField(default='1', max_length=9),
        ),
    ]
