# Generated by Django 3.0.3 on 2020-07-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200726_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='cos',
        ),
        migrations.RemoveField(
            model_name='monthlyschedule',
            name='cos',
        ),
    ]
