# Generated by Django 3.0.3 on 2020-07-25 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateField(default=datetime.datetime(2020, 7, 25, 20, 29, 16, 133711, tzinfo=utc))),
                ('publication_date', models.DateField(default=None, null=True)),
                ('publicized', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.PersonnelProfile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Topic')),
            ],
        ),
    ]
