# Generated by Django 3.0.3 on 2020-07-26 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200726_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 26, 8, 54, 17, 854718, tzinfo=utc)),
        ),
    ]
